apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: austa-backend-hpa
  namespace: austa
  labels:
    app: austa
    component: backend
    environment: production
    tier: application
    managed-by: kubernetes
    version: v1
  annotations:
    description: HPA configuration for AUSTA Integration Platform backend services
    scaling-policy: CPU and Memory based dynamic scaling
    contact: platform-team@austa.com
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: austa-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min