apiVersion: v1
kind: Secret
metadata:
  name: austa-app-secrets
  namespace: austa
  labels:
    app: austa
    component: backend
    environment: production
  annotations:
    rotation.kubernetes.io/last-rotated: "2024-01-01T00:00:00Z"
    rotation.kubernetes.io/next-rotation: "2024-04-01T00:00:00Z"
    audit.kubernetes.io/enabled: "true"
    security.kubernetes.io/encryption-provider: "aes-gcm-256"
type: Opaque
data:
  # Application Secrets
  APP_KEY: ${BASE64_APP_KEY}
  ENCRYPTION_KEY: ${BASE64_ENCRYPTION_KEY}
  BACKUP_ENCRYPTION_KEY: ${BASE64_BACKUP_KEY}

  # Database Credentials - Primary Region
  DB_USERNAME: ${BASE64_DB_USERNAME}
  DB_PASSWORD: ${BASE64_DB_PASSWORD}
  DB_REPLICA_USERNAME: ${BASE64_DB_REPLICA_USERNAME}
  DB_REPLICA_PASSWORD: ${BASE64_DB_REPLICA_PASSWORD}

  # Database Credentials - DR Region
  DR_DB_USERNAME: ${BASE64_DR_DB_USERNAME}
  DR_DB_PASSWORD: ${BASE64_DR_DB_PASSWORD}

  # Redis Credentials
  REDIS_PASSWORD: ${BASE64_REDIS_PASSWORD}
  REDIS_CACHE_PASSWORD: ${BASE64_REDIS_CACHE_PASSWORD}

  # AWS Credentials
  AWS_ACCESS_KEY_ID: ${BASE64_AWS_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${BASE64_AWS_SECRET_KEY}
  AWS_SES_KEY: ${BASE64_AWS_SES_KEY}
  AWS_SES_SECRET: ${BASE64_AWS_SES_SECRET}

  # GCP Credentials for DR
  GCP_PROJECT_ID: ${BASE64_GCP_PROJECT_ID}
  GCP_SERVICE_ACCOUNT: ${BASE64_GCP_SERVICE_ACCOUNT}

  # Vonage Video API Credentials
  VONAGE_API_KEY: ${BASE64_VONAGE_KEY}
  VONAGE_API_SECRET: ${BASE64_VONAGE_SECRET}

  # EMR Integration Credentials
  EMR_API_KEY: ${BASE64_EMR_API_KEY}
  EMR_API_SECRET: ${BASE64_EMR_SECRET}
  EMR_WEBHOOK_SECRET: ${BASE64_EMR_WEBHOOK_SECRET}
  FHIR_CLIENT_ID: ${BASE64_FHIR_CLIENT_ID}
  FHIR_CLIENT_SECRET: ${BASE64_FHIR_CLIENT_SECRET}

  # SSL Certificates
  MYSQL_ATTR_SSL_CA: ${BASE64_RDS_CA_CERT}
  DR_MYSQL_ATTR_SSL_CA: ${BASE64_GCP_SQL_CERT}